export const ADVANCED_LESSONS = [
  "The formula is: Total = (Subtotal * 1.085) + Shipping; where Shipping = $14.95.",
  "ERROR 404: The request at 'https://typemaster.pro/api/v1/battle?room=9928' returned a NullPointerException.",
  "Check validation rules: Password must contain >= 1 uppercase letter, 1 digit, and 1 symbol (like #, $, or %).",
  "Is JavaScript fast? Let's test: const speedTest = () => { return Math.max(88, 92, 104); };",
  "The 1990s saw the birth of the World Wide Web (WWW). By 2026, internet speeds exceeded 10 Gbps!",
  "Are you ready? Press 'Shift + Alt + T' to launch the multiplayer battle terminal; code room #48A.",
  "In software design, standard regex patterns like /^[A-Z_]+[0-9]*$/i are used to test global environments.",
  "Philosophers ask: \"Is truth relative, or absolute?\" Scientific analysis suggests 99.9% of facts are verifiable.",
  "Calculate coordinates: x = (r * cos(theta)) - 12.5; y = (r * sin(theta)) + 45.3; z = -1.0;",
  "Advanced typing requires speed (>=80 WPM), precision (>=98% Acc), and absolute consistency!",
  "Query the database: SELECT id, username, wpm FROM profiles WHERE role = 'admin' ORDER BY wpm DESC LIMIT 10;",
  "Let's initialize a new Git repository: git init && git add . && git commit -m 'Initial commit v1.0.0';",
  "The IP address 192.168.1.104 is hosting a microservice on port 8080. Connect using http://localhost:8080/api.",
  "Regex validation for email: const regex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/;",
  "Can you type these braces and brackets quickly? {[()]} && || != == !== === <= >= += -= *= /=.",
  "Under modern CSS variables: --bg: #0B0B0B; --accent: #FF6B00; --text: rgba(255, 255, 255, 0.95);",
  "In Unix: find . -name '*.js' | grep -v 'node_modules' | xargs wc -l; calculates lines of JS code.",
  "Markdown formatting syntax: Use **bold** text, *italics*, `inline code`, and > blockquotes for layout.",
  "Is this JSON valid? { \"id\": 10839, \"name\": \"TypeMaster Pro\", \"features\": [\"multiplayer\", \"zen-mode\"] }",
  "Execute from directory: cd /var/log/nginx && tail -f access.log | grep -E '404|500|403' --color=always;",
  "The value of Euler's number e is approximately 2.71828, while Pi is 3.14159265358979323846.",
  "Wait, does 0.1 + 0.2 === 0.3 in IEEE 754 floating-point math? No, it returns 0.30000000000000004!",
  "Verify server integrity: md5sum -c sha256sums.txt && openssl dgst -sha256 -verify pubkey.pem -signature sig file.zip",
  "In React: const [state, setState] = useState(() => calculateInitialValue(props.id, 100));",
  "Check system stats: top -b -n 1 | grep 'Cpu(s)' | awk '{print \"Usage: \" $2 + $4 \"%\"}';",
  "Keyboard coordinates: home row indexes are 'F' (left index finger) and 'J' (right index finger).",
  "The default gateway is fe80::1%eth0. Run traceroute6 or ping6 -c 5 google.com to test routing paths.",
  "SQL Query: UPDATE users SET last_login = NOW(), login_count = login_count + 1 WHERE email = 'test@example.com';",
  "Write an arrow function: const double = (arr) => arr.map(x => x * 2).filter(x => x > 10);",
  "Try typing symbols sequentially: ~ ! @ # $ % ^ & * ( ) _ + { } | : \" < > ? ` - = [ ] \\ ; ' , . /",
  "Run Docker container: docker run -d -p 3000:3000 --name web-app -e NODE_ENV=production next-image:latest",
  "In C++: std::vector<std::unique_ptr<Player>> players; players.push_back(std::make_unique<Player>(\"Ajeet\"));",
  "Java configuration: System.setProperty(\"javax.net.ssl.trustStore\", \"/etc/ssl/certs/java/cacerts\");",
  "For loop: for (let i = 0; i < items.length; i++) { console.log(`Item at index ${i}:`, items[i]); }",
  "The constant speed of light in a vacuum is c = 299,792,458 meters per second (about 186,282 miles/s).",
  "Execute package: npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch --minify",
  "Is your code type-safe? Use TypeScript: interface User { readonly id: string; email: string; score?: number; }",
  "To generate a secure key, use node crypto: crypto.randomBytes(32).toString('hex');",
  "Use git rebase: git checkout feature && git rebase main && git push origin feature --force-with-lease;",
  "HTML5 Boilerplate: <!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>App</title></head>",
  "Mathematical theorem: a^2 + b^2 = c^2. Trigonometric identity: sin^2(x) + cos^2(x) = 1.",
  "Python listing: squares = [x**2 for x in range(10) if x % 2 == 0]; print(f\"Even squares: {squares}\")",
  "A secure hash algorithm (SHA-256) outputs a 64-character hexadecimal signature representing 256 bits.",
  "Kubernetes deployment: kubectl apply -f ./k8s/deployment.yaml && kubectl rollout status deployment/web-deployment",
  "In Python: def fetch_data(url: str, timeout: int = 5) -> dict: return requests.get(url, timeout=timeout).json()",
  "Binary conversion: 101010 in binary equals 42 in decimal, while hexadecimal 0x2A is also 42.",
  "TypeScript generics: function identity<T>(arg: T): T { return arg; } const val = identity<string>(\"antigravity\");",
  "To read logs: tail -n 100 /var/log/syslog | awk '{print $5, $6}' | sort | uniq -c | sort -nr;",
  "CSS Flexbox properties: display: flex; flex-direction: row; justify-content: center; align-items: center;",
  "Check active network connections: netstat -an | grep ESTABLISHED | wc -l; or ss -s for summary.",
  "React Router syntax: <Route path=\"/dashboard/:userId/settings\" element={<DashboardSettingsView />} />",
  "Using async/await: const data = await Promise.all([fetch(url1), fetch(url2)]).then(res => Promise.all(res.map(r => r.json())));",
  "The golden ratio is Phi = (1 + Math.sqrt(5)) / 2, which is approximately 1.6180339887.",
  "Create keypair: ssh-keygen -t ed25519 -C \"user@host\" -f ~/.ssh/id_ed25519 -N \"secure_passphrase_123\"",
  "Verify server SSL: openssl s_client -connect typemaster.pro:443 -tls1_3 -showcerts < /dev/null",
  "Git branch cleanup: git branch --merged | grep -v '\\*' | grep -v 'main' | xargs git branch -d",
  "For database indexes: CREATE UNIQUE INDEX idx_user_email_active ON users (email) WHERE status = 'active';",
  "CSS Grid parameters: grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1.5rem;",
  "Docker Compose setup: version: '3.8'\nservices:\n  db:\n    image: postgres:15-alpine\n    ports:\n      - \"5432:5432\"",
  "Check file permissions in Linux: -rwxr-xr-x 1 root root 4096 Jun 28 13:00 script.sh; run chmod +x script.sh",
  "Next.js API route: export async function GET(request: Request) { return NextResponse.json({ success: true }); }",
  "Express routing: app.use('/api/v1/users', require('./routes/users')); app.use(errorHandlerMiddleware);",
  "Use SQL Joins: SELECT u.name, o.total FROM users u INNER JOIN orders o ON u.id = o.user_id WHERE o.status = 'shipped';",
  "In Golang: package main\nimport \"fmt\"\nfunc main() {\n    fmt.Println(\"Go is compiled and fast!\")\n}",
  "Rust safety rules: fn main() {\n    let mut x = 5;\n    let y = &mut x;\n    *y += 1;\n    println!(\"{}\", y);\n}",
  "To search files: find . -type f -name \"*.tsx\" -not -path \"*/node_modules/*\" | xargs grep -n \"useApp\"",
  "MongoDB query: db.users.find({ age: { $gte: 21 } }).sort({ score: -1 }).projection({ name: 1, email: 1 });",
  "Standard HTTP status codes: 200 OK, 201 Created, 301 Moved Permanently, 400 Bad Request, 404 Not Found, 500 Internal Error.",
  "Regular Expression match: const isZipCode = (val) => /^\\d{5}(-\\d{4})?$/.test(val); console.log(isZipCode(\"90210\"));",
  "The Planck constant h is 6.62607015 * 10^-34 Joule-seconds, a fundamental physical constant.",
  "Check TCP listening ports on Windows: netstat -ano | findstr LISTENING | findstr :3000",
  "In Java: public class Singleton {\n    private static final Singleton INSTANCE = new Singleton();\n    public static Singleton getInstance() { return INSTANCE; }\n}",
  "For array manipulation: const unique = [...new Set([1, 2, 2, 3, 4, 4, 5])]; // returns [1, 2, 3, 4, 5]",
  "Run database migration: npx prisma migrate dev --name init_database_schema && npx prisma db seed",
  "Check disk usage in Unix: df -h --max-depth=1 /home; and du -sh * | sort -hr; to find large directories.",
  "TypeScript type guard: function isString(val: unknown): val is string { return typeof val === 'string'; }",
  "In C#: public record UserDto(string Id, string Email, [Required] string Username, int Score);",
  "Secure cookie setup: res.cookie('token', token, { httpOnly: true, secure: true, sameSite: 'strict', maxAge: 3600000 });",
  "Using Curl command: curl -X POST -H \"Content-Type: application/json\" -d '{\"score\":95}' https://api.typemaster.pro/score",
  "For string formatting in Python: print(f\"Accuracy: {correct / total:.2%}\")",
  "In SQL: ALTER TABLE profiles ADD CONSTRAINT fk_user_id FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE;",
  "Write an event listener: window.addEventListener('resize', debounce(() => console.log(window.innerWidth), 250));",
  "To run build output: node .next/standalone/server.js; after running next build with standalone output.",
  "CSS shadow style: box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);",
  "Standard Unix redirect: cat input.txt | tr '[:upper:]' '[:lower:]' | sort | uniq -c > output.txt",
  "In Haskell: quicksort :: (Ord a) => [a] -> [a]\nquicksort [] = []\nquicksort (x:xs) = quicksort [a | a <- xs, a <= x] ++ [x] ++ quicksort [a | a <- xs, a > x]",
  "Initialize React root: const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);",
  "Using Redux selector: const userScore = useSelector((state: RootState) => state.auth.user?.profile.wpm);",
  "Mathematical definition: A matrix is singular if its determinant is exactly zero, meaning it cannot be inverted.",
  "In HTML: <a href=\"https://typemaster.pro\" target=\"_blank\" rel=\"noopener noreferrer\">Typing Platform</a>",
  "Verify package signatures: gpg --keyserver keyserver.ubuntu.com --recv-keys 0xKEYID && gpg --verify file.sig file.tar.gz",
  "Kubernetes pod inspection: kubectl logs -f pod-name-xyz -c container-name --tail=50 --timestamps",
  "TypeScript namespaces: namespace Validation { export interface StringValidator { isAcceptable(s: string): boolean; } }",
  "Create database user: CREATE USER 'typist'@'localhost' IDENTIFIED WITH mysql_native_password BY 'SecurePass123!';",
  "For URL query parameters: const params = new URLSearchParams(window.location.search); const room = params.get('room');",
  "In Python: with open('data.json', 'r', encoding='utf-8') as f: data = json.load(f); print(len(data))",
  "Run background script: nohup node server.js > server.log 2>&1 &; logs everything to server.log and runs in background.",
  "TypeScript utilities: type PartialUser = Partial<User>; type UserKeys = keyof User; type ReadonlyUser = Readonly<User>;",
  "CSS transition parameters: transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); filter: drop-shadow(0 0 8px var(--accent));",
  "Congratulations, you finished the final level! (Level 100: Speed = 120 WPM, Acc = 100%, Error Count = 0)."
];
