export const INTERMEDIATE_LESSONS = [
  "slow and steady wins the race when learning to type correctly",
  "develop healthy habits by practicing short sessions every day",
  "make sure to keep your wrists raised above the desk surfaces",
  "using a mechanical keyboard can improve tactile typing responses",
  "accuracy is more important than raw typing speed at first",
  "focus on keeping your eyes on the screen instead of fingers",
  "proper home row posture reduces hand fatigue over long hours",
  "take frequent breaks to stretch your hands during long sessions",
  "rhythm and consistency build deep muscle memory for letters",
  "typing fast requires relaxed hands and comfortable positioning",
  "the thumb should rest gently on the spacebar at all times",
  "index fingers belong on the keys with small raised bumps",
  "each finger is responsible for a specific column of keys",
  "practice difficult letter combinations slowly until they flow",
  "software developers spend hours typing code and documentation",
  "a quiet typing rhythm is often faster than loud erratic bursts",
  "avoid hammering the keys with excessive force while writing",
  "learning keyboard shortcuts can double your overall productivity",
  "focus on your weak keys to balance your speed across hands",
  "typing tests measure words per minute and error percentages",
  "the spacebar should be struck with the same thumb every time",
  "keep your elbows at a ninety degree angle for best posture",
  "daily typing drills build neural pathways for automatic action",
  "always return your fingers to the home row after each stroke",
  "try to visualize the keyboard layout in your mind as you type",
  "smooth movements are faster than sudden rushes of speed",
  "capital letters require coordinated use of the shift keys",
  "press the shift key with the opposite hand of the letter",
  "balanced practice is the key to steady speed improvements",
  "ergonomic keyboards help prevent repetitive strain injuries",
  "a clean workspace keeps you focused during typing exercises",
  "learning to touch type is a valuable lifetime digital skill",
  "monitor your progress over weeks to see steady speed gains",
  "relax your shoulders to prevent tension from building up",
  "accurate typing saves hours of correction time every week",
  "practice typing common English words to build basic fluency",
  "your typing speed will naturally fluctuate depending on focus",
  "use light keypresses to conserve energy during long tests",
  "mastering the top row numbers requires patient practice",
  "try typing without looking at the keyboard even once today",
  "consistent hand positioning makes typing feel second nature",
  "the pinky finger is responsible for many modifier keys",
  "rushed typing leads to errors which slow down your overall WPM",
  "take a deep breath and find a comfortable typing flow now",
  "adjust your chair height to maintain standard ergonomic angles",
  "typing is a physical skill that improves through repetition",
  "use online tools to track your daily statistics and goals",
  "slow down when you hit a patch of unfamiliar complex words",
  "good posture supports breathing and keeps you alert longer",
  "keep practicing and you will reach your target speed soon",
  "typing fluently allows you to write down thoughts instantly",
  "concentration is key to maintaining high accuracy scores",
  "the index fingers cover the most keys on a standard board",
  "practice punctuation marks to write realistic sentences",
  "try to type with a light tap instead of pushing keys down",
  "resting your palms on the desk can cause wrist strain",
  "each hand handles half of the standard keyboard layout",
  "stretch your fingers and wrists before starting a long test",
  "building muscle memory takes time so remain patient always",
  "typing skills are essential for almost every modern career",
  "aim for ninety five percent accuracy before pushing for speed",
  "focused practice is much better than typing mindlessly",
  "a simple daily routine of ten minutes makes a big difference",
  "keep your movements small and efficient to type faster",
  "try typing in a quiet room to hear your typing rhythm",
  "visualize the path your finger takes to reach each key",
  "a steady pace is more comfortable and leads to fewer typos",
  "use standard fingering for symbols to avoid awkward reaches",
  "your non dominant hand will get faster with regular practice",
  "typing accuracy depends on clean distinct key strikes",
  "take your time on longer words to ensure correct sequence",
  "learning keyboard layouts other than qwerty can be fun",
  "keep your screen at eye level to prevent neck strain",
  "typing games are a fun way to build speed and accuracy",
  "focus on the sound of your keys to check your rhythm",
  "try to maintain a constant speed throughout the passage",
  "practice helps you write emails and documents much faster",
  "your hands will learn where the keys are automatically",
  "use standard home row guides to position your hands blindly",
  "speed increases when you stop thinking about individual letters",
  "comfortable typing setups improve overall work satisfaction",
  "make typing practice a fun break in your daily routine",
  "clean keycaps feel better and improve tactile contact",
  "try to write with a flow that matches your natural breathing",
  "accurate typists spend less time proofreading their work",
  "learning key locations takes dedication but pays off well",
  "use soft lighting to reduce eye strain during typing runs",
  "typing skills are like musical skills requiring practice",
  "aim to type entire short words in a single fluid motion",
  "keep your wrists straight to avoid blocking blood flow",
  "typing is a language translation from thoughts to fingers",
  "regular short breaks keep your mind fresh and hands relaxed",
  "try to type complex character patterns with steady timing",
  "your speed will jump once the layout becomes second nature",
  "focus on standard typing form rather than high WPM numbers",
  "use index fingers for numbers five and six on the top row",
  "typing with friends can make practice sessions more fun",
  "keep your finger joints slightly curved for standard strikes",
  "try to read one or two words ahead of what you type",
  "you are building a skill that will serve you for decades"
];
